plugins:
  - babel
rules:
  # Possible Errors
  comma-dangle:
    - error
    - always-multiline
  no-cond-assign:
    - error
    - always
  no-console: warn
  no-constant-condition:
    - error
    - checkLoops: true
  no-control-regex: off
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens:
    - error
    - all
    - conditionalAssign: false
      nestedBinaryExpressions: true
      returnAssign: false
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations:
    - error
    - both
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: off
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-jsdoc: off
  valid-typeof:
    - error
    - requireStringLiterals: true

  # Best Practices
  accessor-pairs: off
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity: off
  consistent-return: off
  curly:
    - error
    - multi-or-nest
    - consistent
  default-case: off
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq:
    - error
    - always
    - null: always
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: off
  no-else-return: error
  no-empty-function: off
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: off
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: error
  no-native-reassign: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign:
    - error
    - props: false
  no-proto: error
  no-redeclare: error
  no-return-assign:
    - error
    - except-parens
  no-script-url: error
  no-self-assign:
    - error
    - props: true
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  radix: off
  vars-on-top: off
  wrap-iife:
    - error
    - inside
  yoda:
    - error
    - never

  # Strict Mode
  strict:
    - error
    - global

  # Variables
  init-declarations: error
  no-catch-shadow: off
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars: error
  no-use-before-define:
    - error
    - functions: false
      classes: true

  # Node.js and CommonJS
  callback-return: error
  global-require: off
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: off
  no-process-exit: error
  no-restricted-modules: off
  no-restricted-properties: off
  no-sync: off

  # Stylistic Issues
  array-bracket-spacing:
    - error
    - never
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
    - properties: always
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  consistent-this:
    - error
    - self
  eol-last:
    - error
    - unix
  func-call-spacing:
    - error
    - never
  func-names:
    - error
    - always
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  id-blacklist: off
  id-length: off
  id-match: off
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: 1
      outerIIFEBody: 1
      MemberExpression: 1
      FunctionDeclaration:
        parameters: 1
        body: 1
      FunctionExpression:
        parameters: 1
        body: 1
  jsx-quotes: off
  key-spacing:
    - error
    - afterColon: true
      beforeColon: false
      mode: strict
  keyword-spacing:
    - error
    - after: true
      before: true
  line-comment-position:
    - error
    - position: above
  linebreak-style:
    - error
    - unix
  lines-around-comment: off
  lines-around-directive:
    - error
    - always
  max-depth: off
  max-len:
    - error
    - code: 80
      tabWidth: 2
      comments: 80
      ignoreComments: false
      ignoreTrailingComments: false
      ignoreUrls: false
      ignoreStrings: false
      ignoreTemplateLiterals: false
  max-lines: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: off
  multiline-ternary: off
  new-cap:
    - error
    - capIsNew: false
      newIsCap: true
  new-parens: error
  newline-after-var: off
  newline-before-return: off
  newline-per-chained-call: off
  no-array-constructor: off
  no-bitwise: off
  no-continue: off
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-operators:
    - error
    - allowSamePrecedence: true
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-spaced-func: error
  no-tabs: error
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: off
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error 
    - never
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  one-var:
    - error
    - initialized: never
  one-var-declaration-per-line:
    - error
    - initializations
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - before
    - overrides: 
        =: after  
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
      avoidEscape: false
  require-jsdoc: off
  semi:
    - error
    - always
    - omitLastInOneLineBlock: true
  semi-spacing:
    - error
    - after: true
      before: false
  sort-imports:
    - error
    - ignoreCase: true
      memberSyntaxSortOrder:
        - none
        - single
        - multiple
        - all
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
  sort-vars:
    - error
    - ignoreCase: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - always
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment:
    - error
    - always
    - block:
        balanced: true
  unicode-bom:
    - error
    - never
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style:
    - error
    - as-needed
    - requireReturnForObjectLiteral: false
  arrow-parens: off
  arrow-spacing:
    - error
    - after: true
      before: true
  constructor-super: error
  generator-star-spacing: off
  no-class-assign: error
  no-confusing-arrow: off
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports:
    - error
    - includeExports: false
  no-new-symbol: error
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename:
    - error
    - ignoreDestructuring: false
      ignoreExport: false
      ignoreImport: false
  no-var: error
  object-shorthand:
    - error
    - always
    - avoidQuotes: false
      ignoreConstructors: false
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
      allowUnboundThis: false
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  prefer-numeric-literals: error
  prefer-reflect: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  rest-spread-spacing:
    - error
    - never
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  yield-star-spacing:
    - error
    - after: false
      before: true

  # Babel
  babel/arrow-parens:
    - error
    - as-needed
  babel/func-params-comma-dangle:
    - error
    - always-multiline
  babel/generator-star-spacing:
    - error
    - after: true
      before: false
  babel/no-await-in-loop: error
